name: LobiShoutSystem
main: ikatyo\LobiShoutSystem\Main
version: 4.0.0
description: Lobiの指定グループに自動投稿します。
api: 3.0.0-ALPHA10
load: POSTWORLD
author: ikatyo
commands: 
 lobi:
  description: Lobiにメッセージを投稿します。
  usage: /lobi